Nest/Models/Vendor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Nest.Models
{
    public class Vendor:BaseEntity
    {
        [StringLength(45), Required]
        public string? Name { get; set; }
        [StringLength(1500), Required]
        public string? Description { get; set; }
        [StringLength(100), Required]
        public string? Address { get; set; }
        [StringLength(30)]
        public string Number { get; set; }
        public string? ProfileImageUrl { get; set; }
        public string? BackgroundImageUrl { get; set; }
        public int CreatedYear { get; set; }
        public ICollection<Product>? Products { get; set; }
        [NotMapped]
        public IFormFile? ProfileImageFile { get; set; }
        [NotMapped]
        public IFormFile? BackgroundImageFile { get; set; }
    }
}

Nest/Areas/Manage/Controllers/VendorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nest.DAL;
using Nest.Models;
using Nest.Utlis.Enums;
using Nest.Utlis.Extensions;
using System.Net;
using System.Net.Mail;

namespace Nest.Areas.Manage.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class VendorController : Controller
    {
        private readonly NestContext _context;
        private readonly UserManager<AppUser> _userManager;

        public VendorController(NestContext context,
                                UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: VendorController
        public ActionResult Index()
        {
            return View(_context.Vendors.Include(v=>v.Products));
        }

        // GET: VendorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VendorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VendorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vendor vendor)
        {
            if (!ModelState.IsValid) return View();
            if (vendor.ProfileImageFile is null)
            {
                ModelState.AddModelError("ProfileImageFile", "Zəhmət olmasa profil şəklinizi yükləyin");
                return View();
            }
            var profileImg = vendor.ProfileImageFile;
            if (!profileImg.CheckFileExtension("image/"))
            {
                ModelState.AddModelError("ProfileImageFile", "Yüklədiyiniz fayl şəkil deyil");
                return View();
            }
            if (profileImg.CheckFileSize(1))
            {
                ModelState.AddModelError("ProfileImageFile", "Yüklədiyiniz şəkil 2mb-dan artıq olmamalıdır");
                return View();
            }
            string newProfileImgName = Guid.NewGuid() + profileImg.CutFileName();
            profileImg.SaveFile(Path.Combine("imgs", "vendor", newProfileImgName));
            vendor.ProfileImageUrl = newProfileImgName;
            var backImg = vendor.BackgroundImageFile;
            vendor.BackgroundImageUrl = "vendor-header-bg.png";
            if (backImg != null)
            {
                if (!backImg.CheckFileExtension("image/"))
                {
                    ModelState.AddModelError("BackgroundImageUrl", "Yüklədiyiniz fayl şəkil deyil");
                    return View();
                }
                if (backImg.CheckFileSize(1))
                {
                    ModelState.AddModelError("BackgroundImageUrl", "Yüklədiyiniz şəkil 2mb-dan artıq olmamalıdır");
                    return View();
                }
                string newBackImgName = Guid.NewGuid() + backImg.CutFileName();
                backImg.SaveFile(Path.Combine("imgs", "vendor", newBackImgName));
                vendor.BackgroundImageUrl = newBackImgName;
            }
            vendor.IsDeleted = false;
            vendor.Modified = DateTime.UtcNow;
            _context.Vendors.Add(vendor);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: VendorController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VendorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VendorController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VendorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<IActionResult> PendingVendors()
        {
            return View(await _userManager.GetUsersInRoleAsync(Roles.VendorPending.ToString()));
        }
        public async Task<IActionResult> SendInfoMail(string email, bool? isAccepted)
        {
            if (string.IsNullOrWhiteSpace(email) || isAccepted == null) return BadRequest();
            var user = await _userManager.FindByEmailAsync(email);
            if (user is null) return NotFound();
            await _userManager.RemoveFromRoleAsync(user, Roles.VendorPending.ToString());
            if (isAccepted == true)
            {
                await _userManager.AddToRoleAsync(user, Roles.Vendor.ToString());
                SendMail(email,"Info about vendor program","<p style='color:green'>Congragulations</p>");
            }
            else
            {
                await _userManager.AddToRoleAsync(user, Roles.Member.ToString());
                SendMail(email,"Info about vendor program","<p style='color:red'>We are so sorry</p>");
            }
            return RedirectToAction(nameof(Index));
        }
        private void SendMail(string email, string subject, string body)
        {
            string myEmail = "nestmvcproject@gmail.com";
            string pass = "euvmxxtbpinoytxt";

            var from = new MailAddress(myEmail,"Nest support");
            var to = new MailAddress(email);

            SmtpClient smtp = new SmtpClient {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                Credentials = new NetworkCredential(myEmail,pass)
            };
            using (var message = new MailMessage(from, to) { Subject = subject, Body = body,IsBodyHtml=true})
            {
                smtp.Send(message);
            }

        }
    }
}

Nest/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nest.DAL;
using Nest.Models;
using Nest.ViewModels;
using Z.EntityFramework.Plus;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Nest.Controllers
{
    public class VendorController : Controller
    {
        private NestContext _context { get; set; }

        public VendorController(NestContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.Vendors.Include(v=>v.Products).Where(v=>v.IsDeleted==false));
        }

        public IActionResult Details(int? id)
        {
            if (id is null) return RedirectToAction(nameof(Index));
            Vendor vendor = _context.Vendors.FirstOrDefault(v=>v.Id == id);
            if (vendor is null) return NotFound();
            VendorDetailVM detailVM = new VendorDetailVM
            {
                Vendor = _context.Vendors.FirstOrDefault(v => v.Id == id),
                Products = _context.Products.IncludeOptimized(p => p.ProductImages).IncludeOptimized(p => p.Vendor)
                .IncludeOptimized(p => p.Badge).Where(p=>p.IsDeleted==false && p.VendorId == id)
            };
            return View(detailVM);
        }
        public IActionResult Create()
        {

            return View();
        }


    }
}

Nest/Views/Vendor/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model Vendor
<div class="row">
    <div class="col-9">
        <div class="content-header">
            <h2 class="content-title">Satıcı əlavə et</h2>
            <div>
                <button class="btn btn-light rounded font-sm mr-5 text-body hover-up">Save to draft</button>
                <button class="btn btn-md rounded font-sm hover-up">Publich</button>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <form method="post" enctype="multipart/form-data">
            <div class="card mb-4">
                <div class="card-header">
                    <h4>Media</h4>
                </div>
                <div class="card-body">
                    <div>
                        <label class="text-center w-100" asp-for="ProfileImageFile"><img src="~/manage/assets/imgs/theme/upload.svg" alt="" /></label>
                        <input class="form-control" asp-for="ProfileImageFile" />
                        <span class="text-danger" asp-validation-for="ProfileImageFile"></span>
                    </div>
                    <div>
                        <label class="text-center w-100" asp-for="BackgroundImageFile"><img src="~/manage/assets/imgs/theme/upload.svg" alt="" /></label>
                        <input class="form-control" asp-for="BackgroundImageFile" />
                        <span class="text-danger" asp-validation-for="BackgroundImageFile"></span>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" asp-for="Name"></label>
                        <input class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" asp-for="Description"></label>
                        <input class="form-control" asp-for="Description" />
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" asp-for="Address"></label>
                        <input class="form-control" asp-for="Address" />
                        <span class="text-danger" asp-validation-for="Address"></span>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" asp-for="Number"></label>
                        <input class="form-control phone" asp-for="Number" />
                        <span class="text-danger" asp-validation-for="Number"></span>
                    </div>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.phone').inputmask('(999)99-999-99-99');
        });
    </script>

}

Nest/Views/Vendor/Index.cshtml
@{
    ViewData["Title"] = "Vendor Page";
}
@model IEnumerable<Vendor>
<main class="main pages mb-80">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Vendors List
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        <div class="container">
            <div class="archive-header-2 text-center">
                <h1 class="display-2 mb-50">Vendors List</h1>
                <div class="row">
                    <div class="col-lg-5 mx-auto">
                        <div class="sidebar-widget-2 widget_search mb-50">
                            <div class="search-form">
                                <form action="#">
                                    <input type="text" placeholder="Search vendors (by name or ID)..." />
                                    <button type="submit"><i class="fi-rs-search"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-50">
                <div class="col-12 col-lg-8 mx-auto">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We have <strong class="text-brand">@Model.Count()</strong> vendors now</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Mall</a></li>
                                        <li><a href="#">Featured</a></li>
                                        <li><a href="#">Preferred</a></li>
                                        <li><a href="#">Total items</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row vendor-grid">
                @foreach (var vendor in Model)
                {
                    <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            <div class="product-badges product-badges-position product-badges-mrg">
                            </div>
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="vendor-details-1.html">
                                        <img class="default-img" src="~/assets/imgs/vendor/@vendor.ProfileImageUrl" alt="" />
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">@vendor.Products.Count() products</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since @vendor.CreatedYear</span>
                                    </div>
                                    <h4 class="mb-5"><a href="vendor-details-1.html">@vendor.Name</a></h4>

                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="~/assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>@vendor.Address</span></li>
                                            <li><img src="~/assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>@vendor.Number</span></li>
                                        </ul>
                                        <a asp-controller="Vendor" asp-action="Details" asp-route-id="@vendor.Id" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="pagination-area mt-20 mb-20">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                        <li class="page-item"><a class="page-link" href="#">6</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</main>